spring.application.name=order-server
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=YourPass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



